name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Atualiza a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Criar diretório dist
        run: mkdir -p dist

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: andersonmdsantos
          outputs: dist/github-contribution-grid-snake.svg

      - name: Criar a branch output se não existir
        run: |
          git fetch
          if ! git show-ref --verify --quiet refs/remotes/origin/output; then
            git checkout --orphan output
            git commit --allow-empty -m "Criando branch output"
            git push origin output
          fi

      - name: Publicar a animação
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
